name: iadenfender
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0 # Added flame dependency
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3
  http: ^1.2.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.4.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/enemies/gusano.png
    - assets/images/enemies/malware.png
    - assets/images/escenario/mapa1.png
    - assets/images/escenario/inicio.png
    - assets/images/escenario/nivel.jpeg
    - assets/images/base/torre.png
    - assets/images/base/AI.png
    - assets/images/boss/ADWARE.png
    - assets/images/escenario/mapa2.png
    - assets/images/escenario/mapa3.png
    - assets/images/escenario/mapa4.png
    - assets/images/projectiles/projectile1.png
    - assets/images/projectiles/projectile2.png
    - assets/music/menu.mp3
    - assets/music/nivel1.mp3
    - assets/music/nivel2.mp3
    - assets/music/nivel3.mp3
    - assets/music/shop.mp3
