name: iadenfender
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0 # Added flame dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/enemies/gusano.png
    - assets/images/enemies/malware.png
    - assets/images/escenario/mapa1.png
    - assets/images/escenario/inicio.png
    - assets/images/escenario/nivel.jpeg
    - assets/images/base/torre.png
    - assets/images/base/AI.png
    - assets/images/boss/ADWARE.png
